### ISSUE TITLE
Customizing component with classes for responsiveness

### ISSUE THREAD

**Issue by UserSina** [NileshPatel17/ng-multiselect-dropdown#326]
I want to set a dynamic width to the multiselect dropdown using responsive utility classes like so:
```HTML
<ng-multiselect-dropdown
        <!-- Class doesn't work (this is from tailwind if you're curious) -->
        class="w-full md:w-3/4"
        [settings]="dropdownSettings"
        [data]="dropdownList">
</ng-multiselect-dropdown>
```

The best I could do is something like this in my css file, but I would have to write the media queries again for responsiveness.
```SCSS
:host::ng-deep.multiselect-dropdown {
  max-width: 65% !important;
}
```

Is there a way to make utility classes work?
